#!/usr/bin/env bash
# Generate fragments for the Ubuntu interfaces file

TACTIC_BRIDGE=tactic0
TACTIC_IP=172.16.10.1
DEV="10 11 12 13 14"

cat <<__HEADER
auto $TACTIC_BRIDGE
iface $TACTIC_BRIDGE inet static
  address $TACTIC_IP
  netmask 255.255.255.0
  bridge_ports none
  bridge_fd 0
  bridge_stp off

__HEADER

for i in $DEV; do
  cat <<__IFACE
auto tactic$i
iface tactic$i inet manual
  pre-up tunctl -u ubuntu -t \$IFACE; brctl addif $TACTIC_BRIDGE \$IFACE; ifconfig \$IFACE up
  post-down tunctl -d \$IFACE

__IFACE
done
